on:
  push:
    branches:
      - main

jobs:
  relese:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: { fetch-depth: 0 }

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install Yarn
        shell: bash
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Configure Git
        run: |
          git config --global credential.helper "store --file=.git/credentials"
          git config --global user.email "github-automation@gmail.com"
          git config --global user.name "Github Automation"
          echo "https://github.com/${{ github.repository }}:${{ secrets.GH_TOKEN }}" > .git/credentials

      - name: Release affected packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git checkout ${{ github.ref_name }}
          yarn release:affected --base=${{ github.event.before }} --head=${{ github.sha }}
          git push --follow-tags --set-upstream origin ${{ github.ref_name }} 
